'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class aspnetuser
    Public Property Id As String
    Public Property Email As String
    Public Property EmailConfirmed As Boolean
    Public Property PasswordHash As String
    Public Property SecurityStamp As String
    Public Property PhoneNumber As String
    Public Property PhoneNumberConfirmed As Boolean
    Public Property TwoFactorEnabled As Boolean
    Public Property LockoutEndDateUtc As Nullable(Of Date)
    Public Property LockoutEnabled As Boolean
    Public Property AccessFailedCount As Integer
    Public Property UserName As String

    Public Overridable Property aspnetuserclaims As ICollection(Of aspnetuserclaim) = New HashSet(Of aspnetuserclaim)
    Public Overridable Property aspnetuserlogins As ICollection(Of aspnetuserlogin) = New HashSet(Of aspnetuserlogin)
    Public Overridable Property aspnetroles As ICollection(Of aspnetrole) = New HashSet(Of aspnetrole)

End Class
