'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class contraband
    Public Property contraband_id As Integer
    Public Property contraband_desc As String
    Public Property contraband_type_id As Nullable(Of Long)
    Public Property confiscation_type_id As Nullable(Of Long)

End Class
