'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class excess_force
    Public Property excess_force_id As Integer
    Public Property incident_id As Nullable(Of Integer)
    Public Property inmates_connected As String
    Public Property ru_pro_slf_chk As Nullable(Of Boolean)
    Public Property ru_pro_oth_e_chk As Nullable(Of Boolean)
    Public Property ru_prv_esc_chk As Nullable(Of Boolean)
    Public Property ru_sb_inm_nc_chk As Nullable(Of Boolean)
    Public Property ru_sb_vio_in_chk As Nullable(Of Boolean)
    Public Property ru_sb_vio_e_chk As Nullable(Of Boolean)
    Public Property ru_sb_dis_chk As Nullable(Of Boolean)
    Public Property ru_sb_thr_chk As Nullable(Of Boolean)
    Public Property t_frc_phy_chk As Nullable(Of Boolean)
    Public Property t_frc_bat_chk As Nullable(Of Boolean)
    Public Property t_frc_spr_chk As Nullable(Of Boolean)
    Public Property t_frc_fa_chk As Nullable(Of Boolean)
    Public Property t_frc_oth_chk As Nullable(Of Boolean)
    Public Property t_frc_oth_com As String
    Public Property injury As String
    Public Property m_treatment As String
    Public Property m_assess_yn As Nullable(Of Boolean)
    Public Property m_adminst_yn As Nullable(Of Boolean)
    Public Property m_administered As String
    Public Property m_loc_cnter As Nullable(Of Boolean)
    Public Property m_loc_hsp As Nullable(Of Boolean)
    Public Property m_loc_oth As Nullable(Of Boolean)
    Public Property m_loc_oth_com As String
    Public Property wt_nme As String
    Public Property wt_loc_id As Nullable(Of Integer)
    Public Property wt_sect_id As Nullable(Of Integer)
    Public Property officer_id As Nullable(Of Integer)
    Public Property supervisor_id As Nullable(Of Integer)
    Public Property user_id As String
    Public Property location_id As Nullable(Of Integer)
    Public Property section_id As Nullable(Of Integer)
    Public Property team_id As Nullable(Of Integer)

End Class
