'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class incident_involved
    Public Property incident_involved_id As Integer
    Public Property incident_id As Nullable(Of Integer)
    Public Property f_name As String
    Public Property l_name As String
    Public Property age As Nullable(Of Integer)
    Public Property location As Nullable(Of Integer)
    Public Property cell As Nullable(Of Integer)
    Public Property classification As String
    Public Property inmate_sys_id As Nullable(Of Integer)

End Class
