'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class incident
    Public Property incident_id As Integer
    Public Property tango As Nullable(Of Integer)
    Public Property cell As Nullable(Of Integer)
    Public Property inmate_id As Nullable(Of Integer)
    Public Property inmate_sys_id As Nullable(Of Integer)
    Public Property f_name As String
    Public Property m_name As String
    Public Property l_name As String
    Public Property full_name As String
    Public Property dob As Nullable(Of Date)
    Public Property age As Nullable(Of Integer)
    Public Property sex As String
    Public Property attended_program As Nullable(Of Integer)
    Public Property attended_program_name As String
    Public Property incident_date As Nullable(Of Date)
    Public Property trib_sched_date As Nullable(Of Date)
    Public Property incident_time As String
    Public Property search_type As Nullable(Of Integer)
    Public Property violation_id As Nullable(Of Integer)
    Public Property contraband_type_id As Nullable(Of Integer)
    Public Property contraband_item As String
    Public Property quantity As Nullable(Of Integer)
    Public Property unit_id As Nullable(Of Integer)
    Public Property t_case_status As Nullable(Of Integer)
    Public Property t_data As String
    Public Property officer_involved As Nullable(Of Integer)
    Public Property officer_conducting As Nullable(Of Integer)
    Public Property officer_reporting As Nullable(Of Integer)
    Public Property officer_supervisor_id As Nullable(Of Integer)
    Public Property comment As String
    Public Property team_id As Nullable(Of Integer)
    Public Property user_id As String
    Public Property rd_to_pa As Boolean
    Public Property rd_to_im As Boolean
    Public Property rd_to_tft As Boolean
    Public Property rd_to_pua As Boolean
    Public Property rd_to_dtp As Boolean
    Public Property rd_to_agod As Boolean
    Public Property rd_to_db As Boolean
    Public Property rd_to_rco As Boolean
    Public Property rd_to_thwds As Boolean
    Public Property rd_to_fa As Boolean
    Public Property rd_to_ep As Boolean
    Public Property rd_to_ea As Boolean
    Public Property rd_to_sat As Boolean
    Public Property rd_to_oth As Boolean
    Public Property violation_oth As String
    Public Property rd_con_cel As Boolean
    Public Property rd_con_cel_qty As Nullable(Of Integer)
    Public Property rd_con_cel_uid As Nullable(Of Integer)
    Public Property rd_con_csh As Boolean
    Public Property rd_con_csh_qty As Nullable(Of Decimal)
    Public Property rd_con_csh_uid As Nullable(Of Integer)
    Public Property rd_con_sim As Boolean
    Public Property rd_con_sim_qty As Nullable(Of Integer)
    Public Property rd_con_sim_uid As Nullable(Of Integer)
    Public Property rd_con_wn As Boolean
    Public Property rd_con_wn_qty As Nullable(Of Decimal)
    Public Property rd_con_wn_uid As Nullable(Of Integer)
    Public Property rd_con_bor As Boolean
    Public Property rd_con_bor_qty As Nullable(Of Integer)
    Public Property rd_con_bor_uid As Nullable(Of Integer)
    Public Property rd_con_drg As Boolean
    Public Property rd_con_drg_qty As Nullable(Of Integer)
    Public Property rd_con_drg_uid As Nullable(Of Integer)
    Public Property rd_con_can As Boolean
    Public Property rd_con_can_qty As Nullable(Of Decimal)
    Public Property rd_con_can_uid As Nullable(Of Integer)
    Public Property rd_con_oth As Boolean
    Public Property rd_con_oth_qty As Nullable(Of Decimal)
    Public Property rd_con_oth_uid As Nullable(Of Integer)
    Public Property rd_con_prn As Boolean
    Public Property rd_con_prn_qty As Nullable(Of Decimal)
    Public Property rd_con_prn_uid As Nullable(Of Integer)
    Public Property offence_nature_oth As String
    Public Property contraband_oth As String
    Public Property reason_oth As String
    Public Property weapon_oth As String
    Public Property weapon_id As Nullable(Of Integer)
    Public Property reason_id As Nullable(Of Integer)
    Public Property contraband_id As Nullable(Of Integer)
    Public Property contraband_unit As Nullable(Of Integer)
    Public Property conceal_method As String
    Public Property offence_nature_id As Nullable(Of Integer)
    Public Property misc_occurrence As String
    Public Property rad_wt_inmate As Boolean
    Public Property rad_wt_officer As Boolean
    Public Property rad_wt_civilian As Boolean
    Public Property rad_wt_none As Boolean
    Public Property wt_inmate_nme As String
    Public Property wt_officer_nme As String
    Public Property wt_civilian_nme As String
    Public Property wt_officer_loc_id As Nullable(Of Integer)
    Public Property wt_civilian_loc_id As Nullable(Of Integer)
    Public Property wt_inmate_loc_id As Nullable(Of Integer)
    Public Property wt_inmate_cell_id As Nullable(Of Integer)
    Public Property wt_inmate_oth As String
    Public Property wt_civilian_oth As String
    Public Property wt_officer_oth As String
    Public Property action_taken As String
    Public Property at_yn_trans_inmate As Boolean
    Public Property at_location_id As Nullable(Of Integer)
    Public Property at_cell_id As Nullable(Of Integer)
    Public Property at_yn_form_cmp As Boolean
    Public Property at_yn_chgtrib As Boolean
    Public Property at_yn_exforce_cmp As Boolean
    Public Property at_other As String
    Public Property civilian As String
    Public Property form_type_id As Byte

End Class
