'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class age
    Public Property age_id As Long
    Public Property a_age As String
    Public Property a_range As String

End Class
Partial Public Class aspnetrole
    Public Property Id As String
    Public Property Name As String

    Public Overridable Property aspnetusers As ICollection(Of aspnetuser) = New HashSet(Of aspnetuser)

End Class
Partial Public Class aspnetuser
    Public Property Id As String
    Public Property Email As String
    Public Property EmailConfirmed As Boolean
    Public Property PasswordHash As String
    Public Property SecurityStamp As String
    Public Property PhoneNumber As String
    Public Property PhoneNumberConfirmed As Boolean
    Public Property TwoFactorEnabled As Boolean
    Public Property LockoutEndDateUtc As Nullable(Of Date)
    Public Property LockoutEnabled As Boolean
    Public Property AccessFailedCount As Integer
    Public Property UserName As String

    Public Overridable Property aspnetuserclaims As ICollection(Of aspnetuserclaim) = New HashSet(Of aspnetuserclaim)
    Public Overridable Property aspnetuserlogins As ICollection(Of aspnetuserlogin) = New HashSet(Of aspnetuserlogin)
    Public Overridable Property aspnetroles As ICollection(Of aspnetrole) = New HashSet(Of aspnetrole)

End Class
Partial Public Class aspnetuserclaim
    Public Property Id As Integer
    Public Property UserId As String
    Public Property ClaimType As String
    Public Property ClaimValue As String

    Public Overridable Property aspnetuser As aspnetuser

End Class
Partial Public Class aspnetuserlogin
    Public Property LoginProvider As String
    Public Property ProviderKey As String
    Public Property UserId As String

    Public Overridable Property aspnetuser As aspnetuser

End Class
Partial Public Class civilian
    Public Property civilian_id As Long
    Public Property f_name As String
    Public Property m_name As String
    Public Property l_name As String
    Public Property age As Nullable(Of Long)
    Public Property sex As String
    Public Property p_location_id As Long

End Class
Partial Public Class confiscation_type
    Public Property confiscation_type_id As Long
    Public Property cnf_name As String

End Class
Partial Public Class contraband
    Public Property contraband_id As Integer
    Public Property contraband_desc As String
    Public Property contraband_type_id As Nullable(Of Long)
    Public Property confiscation_type_id As Nullable(Of Long)

End Class
Partial Public Class contraband_type
    Public Property contraband_type_id As Integer
    Public Property ct_name As String

End Class
Partial Public Class country
    Public Property country_id As Long
    Public Property c_name As String

End Class
Partial Public Class dest_type
    Public Property dest_type_id As Integer
    Public Property d_code As String
    Public Property d_description As String

End Class
Partial Public Class excess_force
    Public Property excess_force_id As Integer
    Public Property incident_id As Nullable(Of Integer)
    Public Property inmates_connected As String
    Public Property ru_pro_slf_chk As Nullable(Of Boolean)
    Public Property ru_pro_oth_e_chk As Nullable(Of Boolean)
    Public Property ru_prv_esc_chk As Nullable(Of Boolean)
    Public Property ru_sb_inm_nc_chk As Nullable(Of Boolean)
    Public Property ru_sb_vio_in_chk As Nullable(Of Boolean)
    Public Property ru_sb_vio_e_chk As Nullable(Of Boolean)
    Public Property ru_sb_dis_chk As Nullable(Of Boolean)
    Public Property ru_sb_thr_chk As Nullable(Of Boolean)
    Public Property t_frc_phy_chk As Nullable(Of Boolean)
    Public Property t_frc_bat_chk As Nullable(Of Boolean)
    Public Property t_frc_spr_chk As Nullable(Of Boolean)
    Public Property t_frc_fa_chk As Nullable(Of Boolean)
    Public Property t_frc_oth_chk As Nullable(Of Boolean)
    Public Property t_frc_oth_com As String
    Public Property injury As String
    Public Property m_treatment As String
    Public Property m_assess_yn As Nullable(Of Boolean)
    Public Property m_adminst_yn As Nullable(Of Boolean)
    Public Property m_administered As String
    Public Property m_loc_cnter As Nullable(Of Boolean)
    Public Property m_loc_hsp As Nullable(Of Boolean)
    Public Property m_loc_oth As Nullable(Of Boolean)
    Public Property m_loc_oth_com As String
    Public Property wt_nme As String
    Public Property wt_loc_id As Nullable(Of Integer)
    Public Property wt_sect_id As Nullable(Of Integer)
    Public Property officer_id As Nullable(Of Integer)
    Public Property supervisor_id As Nullable(Of Integer)
    Public Property user_id As String
    Public Property location_id As Nullable(Of Integer)
    Public Property section_id As Nullable(Of Integer)
    Public Property team_id As Nullable(Of Integer)

End Class
Partial Public Class form_type
    Public Property form_type_id As Long
    Public Property description As String

End Class
Partial Public Class incident
    Public Property incident_id As Integer
    Public Property tango As Nullable(Of Integer)
    Public Property cell As Nullable(Of Integer)
    Public Property inmate_id As Nullable(Of Integer)
    Public Property inmate_sys_id As Nullable(Of Integer)
    Public Property f_name As String
    Public Property m_name As String
    Public Property l_name As String
    Public Property full_name As String
    Public Property dob As Nullable(Of Date)
    Public Property age As Nullable(Of Integer)
    Public Property sex As String
    Public Property attended_program As Nullable(Of Integer)
    Public Property attended_program_name As String
    Public Property incident_date As Nullable(Of Date)
    Public Property trib_sched_date As Nullable(Of Date)
    Public Property incident_time As String
    Public Property search_type As Nullable(Of Integer)
    Public Property violation_id As Nullable(Of Integer)
    Public Property contraband_type_id As Nullable(Of Integer)
    Public Property contraband_item As String
    Public Property quantity As Nullable(Of Integer)
    Public Property unit_id As Nullable(Of Integer)
    Public Property t_case_status As Nullable(Of Integer)
    Public Property t_data As String
    Public Property officer_involved As Nullable(Of Integer)
    Public Property officer_conducting As Nullable(Of Integer)
    Public Property officer_reporting As Nullable(Of Integer)
    Public Property officer_supervisor_id As Nullable(Of Integer)
    Public Property comment As String
    Public Property team_id As Nullable(Of Integer)
    Public Property user_id As String
    Public Property rd_to_pa As Boolean
    Public Property rd_to_im As Boolean
    Public Property rd_to_tft As Boolean
    Public Property rd_to_pua As Boolean
    Public Property rd_to_dtp As Boolean
    Public Property rd_to_agod As Boolean
    Public Property rd_to_db As Boolean
    Public Property rd_to_rco As Boolean
    Public Property rd_to_thwds As Boolean
    Public Property rd_to_fa As Boolean
    Public Property rd_to_ep As Boolean
    Public Property rd_to_ea As Boolean
    Public Property rd_to_sat As Boolean
    Public Property rd_to_oth As Boolean
    Public Property violation_oth As String
    Public Property rd_con_cel As Boolean
    Public Property rd_con_cel_qty As Nullable(Of Integer)
    Public Property rd_con_cel_uid As Nullable(Of Integer)
    Public Property rd_con_csh As Boolean
    Public Property rd_con_csh_qty As Nullable(Of Decimal)
    Public Property rd_con_csh_uid As Nullable(Of Integer)
    Public Property rd_con_sim As Boolean
    Public Property rd_con_sim_qty As Nullable(Of Integer)
    Public Property rd_con_sim_uid As Nullable(Of Integer)
    Public Property rd_con_wn As Boolean
    Public Property rd_con_wn_qty As Nullable(Of Decimal)
    Public Property rd_con_wn_uid As Nullable(Of Integer)
    Public Property rd_con_bor As Boolean
    Public Property rd_con_bor_qty As Nullable(Of Integer)
    Public Property rd_con_bor_uid As Nullable(Of Integer)
    Public Property rd_con_drg As Boolean
    Public Property rd_con_drg_qty As Nullable(Of Integer)
    Public Property rd_con_drg_uid As Nullable(Of Integer)
    Public Property rd_con_can As Boolean
    Public Property rd_con_can_qty As Nullable(Of Decimal)
    Public Property rd_con_can_uid As Nullable(Of Integer)
    Public Property rd_con_oth As Boolean
    Public Property rd_con_oth_qty As Nullable(Of Decimal)
    Public Property rd_con_oth_uid As Nullable(Of Integer)
    Public Property rd_con_prn As Boolean
    Public Property rd_con_prn_qty As Nullable(Of Decimal)
    Public Property rd_con_prn_uid As Nullable(Of Integer)
    Public Property offence_nature_oth As String
    Public Property contraband_oth As String
    Public Property reason_oth As String
    Public Property weapon_oth As String
    Public Property weapon_id As Nullable(Of Integer)
    Public Property reason_id As Nullable(Of Integer)
    Public Property contraband_id As Nullable(Of Integer)
    Public Property contraband_unit As Nullable(Of Integer)
    Public Property conceal_method As String
    Public Property offence_nature_id As Nullable(Of Integer)
    Public Property misc_occurrence As String
    Public Property rad_wt_inmate As Boolean
    Public Property rad_wt_officer As Boolean
    Public Property rad_wt_civilian As Boolean
    Public Property rad_wt_none As Boolean
    Public Property wt_inmate_nme As String
    Public Property wt_officer_nme As String
    Public Property wt_civilian_nme As String
    Public Property wt_officer_loc_id As Nullable(Of Integer)
    Public Property wt_civilian_loc_id As Nullable(Of Integer)
    Public Property wt_inmate_loc_id As Nullable(Of Integer)
    Public Property wt_inmate_cell_id As Nullable(Of Integer)
    Public Property wt_inmate_oth As String
    Public Property wt_civilian_oth As String
    Public Property wt_officer_oth As String
    Public Property action_taken As String
    Public Property at_yn_trans_inmate As Boolean
    Public Property at_location_id As Nullable(Of Integer)
    Public Property at_cell_id As Nullable(Of Integer)
    Public Property at_yn_form_cmp As Boolean
    Public Property at_yn_chgtrib As Boolean
    Public Property at_yn_exforce_cmp As Boolean
    Public Property at_other As String
    Public Property civilian As String
    Public Property form_type_id As Byte

End Class
Partial Public Class incident_involved
    Public Property incident_involved_id As Integer
    Public Property incident_id As Nullable(Of Integer)
    Public Property f_name As String
    Public Property l_name As String
    Public Property age As Nullable(Of Integer)
    Public Property location As Nullable(Of Integer)
    Public Property cell As Nullable(Of Integer)
    Public Property classification As String
    Public Property inmate_sys_id As Nullable(Of Integer)

End Class
Partial Public Class inmate
    Public Property inmate_id As Integer
    Public Property inmate_sys_id As Nullable(Of Integer)
    Public Property f_name As String
    Public Property m_name As String
    Public Property l_name As String
    Public Property full_name As String
    Public Property admiss_dte As Nullable(Of Date)
    Public Property dob As Nullable(Of Date)
    Public Property age As Nullable(Of Integer)
    Public Property o_age As Nullable(Of Integer)
    Public Property sex As String
    Public Property ethnicity_id As Nullable(Of Integer)
    Public Property attended_program As String
    Public Property location_parent_id As Nullable(Of Integer)
    Public Property location_id As Nullable(Of Integer)
    Public Property country_id As Nullable(Of Integer)
    Public Property inmate_status_id As Nullable(Of Integer)
    Public Property custody_status_id As Nullable(Of Integer)
    Public Property i_photo As Byte()

End Class
Partial Public Class inmate_program
    Public Property inmate_program_id As Integer
    Public Property inmate_id As Nullable(Of Integer)
    Public Property program_id As Nullable(Of Integer)

End Class
Partial Public Class interval
    Public Property interval_id As Integer
    Public Property interval_name As String

End Class
Partial Public Class location
    Public Property location_id As Integer
    Public Property location_parent_id As Nullable(Of Integer)
    Public Property tango As String
    Public Property location_name As String

End Class
Partial Public Class location_parent
    Public Property location_parent_id As Integer
    Public Property tango As String
    Public Property description As String
    Public Property move_type_det_id As Nullable(Of Integer)

End Class
Partial Public Class move
    Public Property move_id As Long
    Public Property person_id As Nullable(Of Integer)
    Public Property m_date As Date
    Public Property s_location_id As Nullable(Of Integer)
    Public Property s_time As Date
    Public Property e_location_id As Nullable(Of Integer)
    Public Property e_time As Date
    Public Property move_type_id As Nullable(Of Integer)
    Public Property m_status_id As Nullable(Of Integer)
    Public Property m_comments As String
    Public Property ext_no As String

End Class
Partial Public Class move_type
    Public Property move_type_id As Long
    Public Property m_code As String
    Public Property m_description As String
    Public Property dest_type_id As Nullable(Of Integer)

End Class
Partial Public Class move_type_det
    Public Property move_type_det_id As Integer
    Public Property move_type_id As Nullable(Of Integer)
    Public Property description As String
    Public Property short_desc As String

End Class
Partial Public Class offence_nature
    Public Property offence_nature_id As Integer
    Public Property offence_nature_desc As String

End Class
Partial Public Class officer
    Public Property officer_id As Integer
    Public Property f_name As String
    Public Property m_name As String
    Public Property l_name As String
    Public Property age As Nullable(Of Integer)
    Public Property sex As String
    Public Property p_location_id As Nullable(Of Integer)

End Class
Partial Public Class p_location
    Public Property p_location_id As Integer
    Public Property p_name As String

End Class
Partial Public Class param
    Public Property param_id As Integer
    Public Property par_code As Integer
    Public Property par_num As Integer
    Public Property par_desc As String
    Public Property par_charfield As String
    Public Property recordstamp As Date
    Public Property par_numfield As Nullable(Of Integer)
    Public Property par_table_name As String

End Class
Partial Public Class program
    Public Property program_id As Integer
    Public Property program_class As String

End Class
Partial Public Class reason
    Public Property reason_id As Integer
    Public Property reason_desc As String

End Class
Partial Public Class search_type
    Public Property search_type_id As Integer
    Public Property st_name As String

End Class
Partial Public Class t_verdict
    Public Property t_verdict_id As Integer
    Public Property t_verdict1 As String

End Class
Partial Public Class team
    Public Property team_id As Integer
    Public Property team_name As String

End Class
Partial Public Class tribunal
    Public Property tribunal_id As Integer
    Public Property user_id As String
    Public Property incident_id As Nullable(Of Integer)
    Public Property inmate_id As Nullable(Of Integer)
    Public Property t_date As Date
    Public Property t_time As String
    Public Property v_act As Nullable(Of Integer)
    Public Property t_plea As Nullable(Of Integer)
    Public Property t_verdict As Nullable(Of Integer)
    Public Property charge As String
    Public Property sentence As String
    Public Property comments As String
    Public Property incident_date As Nullable(Of Date)
    Public Property t_officer As Nullable(Of Integer)
    Public Property i_officer As Nullable(Of Integer)
    Public Property v_location As String
    Public Property contraband_item As String
    Public Property t_case_status As Nullable(Of Integer)
    Public Property inmate_name As String
    Public Property v_section As Nullable(Of Integer)
    Public Property chk_st_caution As Boolean
    Public Property chk_st_suspend As Boolean
    Public Property chk_st_full As Boolean
    Public Property chk_st_loss_fd As Boolean
    Public Property chk_st_build As Boolean
    Public Property chk_st_lcv As Boolean
    Public Property chk_st_personal As Boolean
    Public Property chk_st_forfeitwg As Boolean
    Public Property chk_st_losswg As Boolean
    Public Property s_start_date As Nullable(Of Date)
    Public Property sb_start_date As Nullable(Of Date)
    Public Property ss_start_date As Nullable(Of Date)
    Public Property s_lfd_start_date As Nullable(Of Date)
    Public Property s_lcv_start_date As Nullable(Of Date)
    Public Property s_pp_start_date As Nullable(Of Date)
    Public Property s_fw_start_date As Nullable(Of Date)
    Public Property s_lw_start_date As Nullable(Of Date)
    Public Property s_end_date As Nullable(Of Date)
    Public Property sb_end_date As Nullable(Of Date)
    Public Property ss_end_date As Nullable(Of Date)
    Public Property s_lfd_end_date As Nullable(Of Date)
    Public Property s_lcv_end_date As Nullable(Of Date)
    Public Property s_pp_end_date As Nullable(Of Date)
    Public Property s_fw_end_date As Nullable(Of Date)
    Public Property s_lw_end_date As Nullable(Of Date)
    Public Property s_duration As String
    Public Property sb_duration As String
    Public Property ss_duration As String
    Public Property s_lfd_duration As String
    Public Property s_lcv_duration As String
    Public Property s_pp_duration As String
    Public Property s_fw_duration As String
    Public Property s_lw_duration As String
    Public Property s_location_id As Nullable(Of Integer)
    Public Property sb_location_id As Nullable(Of Integer)
    Public Property s_cell_id As Nullable(Of Integer)
    Public Property sb_cell_id As Nullable(Of Integer)
    Public Property s_pp_comments As String
    Public Property chk_pr_council As Boolean
    Public Property chk_pr_medic As Boolean
    Public Property chk_pr_mediate As Boolean
    Public Property chk_pr_oth As Boolean
    Public Property pr_council_com As String
    Public Property pr_medic_com As String
    Public Property pr_mediate_com As String
    Public Property pr_oth_com As String
    Public Property v_act_code_id As Nullable(Of Integer)
    Public Property t_panel_name As String

End Class
Partial Public Class u_locale
    Public Property u_local_id As Long
    Public Property uid As Long
    Public Property loc_parent_id As Nullable(Of Long)

End Class
Partial Public Class u_module
    Public Property u_module_id As Integer
    Public Property u_module_name As String
    Public Property u_mod_desc As String
    Public Property u_mod_group As String

End Class
Partial Public Class u_permissions
    Public Property u_permissions_id As Integer
    Public Property user_id As Integer
    Public Property u_module_id As Integer
    Public Property u_module_all As Integer
    Public Property u_r As Integer
    Public Property u_rw As Integer
    Public Property u_rwa As Integer
    Public Property u_rd As Integer
    Public Property u_rwd As Integer

End Class
Partial Public Class unit
    Public Property unit_id As Integer
    Public Property unit_desc As String
    Public Property unit_abbr As String

End Class
Partial Public Class user
    Public Property user_id As Integer
    Public Property u_name As String
    Public Property u_password As String
    Public Property u_group As String
    Public Property f_name As String
    Public Property l_name As String

End Class
Partial Public Class v_act_code
    Public Property v_act_code_id As Integer
    Public Property violation_act_id As Nullable(Of Integer)
    Public Property reporting_code As String
    Public Property r_short_desc As String
    Public Property r_code_desc As String

End Class
Partial Public Class violation
    Public Property violation_id As Integer
    Public Property offence_name As String
    Public Property short_desc As String

End Class
Partial Public Class violation_act
    Public Property violation_act_id As Integer
    Public Property violation_id As Nullable(Of Integer)
    Public Property v_section As String
    Public Property v_section_desc As String
    Public Property v_subsection As String
    Public Property v_subsection_desc As String

End Class
Partial Public Class weapon
    Public Property weapon_id As Integer
    Public Property weapon_desc As String

End Class
