'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class inmate_program
    Public Property inmate_program_id As Integer
    Public Property inmate_id As Nullable(Of Integer)
    Public Property program_id As Nullable(Of Integer)

End Class
