'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class location_parent
    Public Property location_parent_id As Integer
    Public Property tango As String
    Public Property description As String
    Public Property move_type_det_id As Nullable(Of Integer)

End Class
