'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class move_type_det
    Public Property move_type_det_id As Integer
    Public Property move_type_id As Nullable(Of Integer)
    Public Property description As String
    Public Property short_desc As String

End Class
