'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class move
    Public Property move_id As Long
    Public Property person_id As Nullable(Of Integer)
    Public Property m_date As Date
    Public Property s_location_id As Nullable(Of Integer)
    Public Property s_time As Date
    Public Property e_location_id As Nullable(Of Integer)
    Public Property e_time As Date
    Public Property move_type_id As Nullable(Of Integer)
    Public Property m_status_id As Nullable(Of Integer)
    Public Property m_comments As String
    Public Property ext_no As String

End Class
