'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class officer
    Public Property officer_id As Integer
    Public Property f_name As String
    Public Property m_name As String
    Public Property l_name As String
    Public Property age As Nullable(Of Integer)
    Public Property sex As String
    Public Property p_location_id As Nullable(Of Integer)

End Class
