'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class param
    Public Property param_id As Integer
    Public Property par_code As Integer
    Public Property par_num As Integer
    Public Property par_desc As String
    Public Property par_charfield As String
    Public Property recordstamp As Date
    Public Property par_numfield As Nullable(Of Integer)
    Public Property par_table_name As String

End Class
