'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tribunal
    Public Property tribunal_id As Integer
    Public Property user_id As String
    Public Property incident_id As Nullable(Of Integer)
    Public Property inmate_id As Nullable(Of Integer)
    Public Property t_date As Date
    Public Property t_time As String
    Public Property v_act As Nullable(Of Integer)
    Public Property t_plea As Nullable(Of Integer)
    Public Property t_verdict As Nullable(Of Integer)
    Public Property charge As String
    Public Property sentence As String
    Public Property comments As String
    Public Property incident_date As Nullable(Of Date)
    Public Property t_officer As Nullable(Of Integer)
    Public Property i_officer As Nullable(Of Integer)
    Public Property v_location As String
    Public Property contraband_item As String
    Public Property t_case_status As Nullable(Of Integer)
    Public Property inmate_name As String
    Public Property v_section As Nullable(Of Integer)
    Public Property chk_st_caution As Boolean
    Public Property chk_st_suspend As Boolean
    Public Property chk_st_full As Boolean
    Public Property chk_st_loss_fd As Boolean
    Public Property chk_st_build As Boolean
    Public Property chk_st_lcv As Boolean
    Public Property chk_st_personal As Boolean
    Public Property chk_st_forfeitwg As Boolean
    Public Property chk_st_losswg As Boolean
    Public Property s_start_date As Nullable(Of Date)
    Public Property sb_start_date As Nullable(Of Date)
    Public Property ss_start_date As Nullable(Of Date)
    Public Property s_lfd_start_date As Nullable(Of Date)
    Public Property s_lcv_start_date As Nullable(Of Date)
    Public Property s_pp_start_date As Nullable(Of Date)
    Public Property s_fw_start_date As Nullable(Of Date)
    Public Property s_lw_start_date As Nullable(Of Date)
    Public Property s_end_date As Nullable(Of Date)
    Public Property sb_end_date As Nullable(Of Date)
    Public Property ss_end_date As Nullable(Of Date)
    Public Property s_lfd_end_date As Nullable(Of Date)
    Public Property s_lcv_end_date As Nullable(Of Date)
    Public Property s_pp_end_date As Nullable(Of Date)
    Public Property s_fw_end_date As Nullable(Of Date)
    Public Property s_lw_end_date As Nullable(Of Date)
    Public Property s_duration As String
    Public Property sb_duration As String
    Public Property ss_duration As String
    Public Property s_lfd_duration As String
    Public Property s_lcv_duration As String
    Public Property s_pp_duration As String
    Public Property s_fw_duration As String
    Public Property s_lw_duration As String
    Public Property s_location_id As Nullable(Of Integer)
    Public Property sb_location_id As Nullable(Of Integer)
    Public Property s_cell_id As Nullable(Of Integer)
    Public Property sb_cell_id As Nullable(Of Integer)
    Public Property s_pp_comments As String
    Public Property chk_pr_council As Boolean
    Public Property chk_pr_medic As Boolean
    Public Property chk_pr_mediate As Boolean
    Public Property chk_pr_oth As Boolean
    Public Property pr_council_com As String
    Public Property pr_medic_com As String
    Public Property pr_mediate_com As String
    Public Property pr_oth_com As String
    Public Property v_act_code_id As Nullable(Of Integer)
    Public Property t_panel_name As String

End Class
