'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class u_module
    Public Property u_module_id As Integer
    Public Property u_module_name As String
    Public Property u_mod_desc As String
    Public Property u_mod_group As String

End Class
