'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class u_permissions
    Public Property u_permissions_id As Integer
    Public Property user_id As Integer
    Public Property u_module_id As Integer
    Public Property u_module_all As Integer
    Public Property u_r As Integer
    Public Property u_rw As Integer
    Public Property u_rwa As Integer
    Public Property u_rd As Integer
    Public Property u_rwd As Integer

End Class
