'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class v_act_code
    Public Property v_act_code_id As Integer
    Public Property violation_act_id As Nullable(Of Integer)
    Public Property reporting_code As String
    Public Property r_short_desc As String
    Public Property r_code_desc As String

End Class
