'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class violation_act
    Public Property violation_act_id As Integer
    Public Property violation_id As Nullable(Of Integer)
    Public Property v_section As String
    Public Property v_section_desc As String
    Public Property v_subsection As String
    Public Property v_subsection_desc As String

End Class
